apiVersion: v1
kind: ConfigMap
metadata:
  name: polardb-sms-manager
  namespace: kube-system
data:
  app_conf: |
    [server]
    port=2002
    id=1
    [cluster]
    vip=10.11.11.11
    mode=docker
    [log]
    level=INFO
