apiVersion: v1
data:
  enableResourceShare: "true"
  normal: |
    single:
      manager:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
    readWriteMany:
      pfsdTool:
        limits:
          cpu: 200m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 1Gi
      pfsd:
        limits:
          cpu: 3800m
          memory: 7Gi
        requests:
          cpu: 3800m
          memory: 7Gi
      manager:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 128Mi
  shared: |
    single:
      manager:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
    readWriteMany:
      pfsdTool:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 256Mi
      pfsd:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 256Mi
      manager:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 500m
          memory: 128Mi
    maxscale:
      operator:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 1000m
          memory: 1Gi
kind: ConfigMap
metadata:
  name: instance-system-resources
  namespace: kube-system