# permissions for end users to view mpdlocalvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpdlocalvolume-viewer-role
rules:
- apiGroups:
  - mpd.polardb.aliyun.com
  resources:
  - mpdlocalvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mpd.polardb.aliyun.com
  resources:
  - mpdlocalvolumes/status
  verbs:
  - get
