/* 
*Copyright (c) 2019-2021, Alibaba Group Holding Limited;
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at

*   http://www.apache.org/licenses/LICENSE-2.0

*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
 */


// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalResourceCfg) DeepCopyInto(out *AdditionalResourceCfg) {
	*out = *in
	out.CPUCores = in.CPUCores.DeepCopy()
	out.LimitMemory = in.LimitMemory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalResourceCfg.
func (in *AdditionalResourceCfg) DeepCopy() *AdditionalResourceCfg {
	if in == nil {
		return nil
	}
	out := new(AdditionalResourceCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBInstanceNetInfo) DeepCopyInto(out *DBInstanceNetInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBInstanceNetInfo.
func (in *DBInstanceNetInfo) DeepCopy() *DBInstanceNetInfo {
	if in == nil {
		return nil
	}
	out := new(DBInstanceNetInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMaxScaleStatus) DeepCopyInto(out *DBMaxScaleStatus) {
	*out = *in
	if in.WorkingAddr != nil {
		in, out := &in.WorkingAddr, &out.WorkingAddr
		*out = make([]DBInstanceNetInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMaxScaleStatus.
func (in *DBMaxScaleStatus) DeepCopy() *DBMaxScaleStatus {
	if in == nil {
		return nil
	}
	out := new(DBMaxScaleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBNetConfig) DeepCopyInto(out *DBNetConfig) {
	*out = *in
	if in.LeaderFloatingIP != nil {
		in, out := &in.LeaderFloatingIP, &out.LeaderFloatingIP
		*out = new(FloatingIPAddr)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBNetConfig.
func (in *DBNetConfig) DeepCopy() *DBNetConfig {
	if in == nil {
		return nil
	}
	out := new(DBNetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatingIPAddr) DeepCopyInto(out *FloatingIPAddr) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatingIPAddr.
func (in *FloatingIPAddr) DeepCopy() *FloatingIPAddr {
	if in == nil {
		return nil
	}
	out := new(FloatingIPAddr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceClassInfo) DeepCopyInto(out *InstanceClassInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceClassInfo.
func (in *InstanceClassInfo) DeepCopy() *InstanceClassInfo {
	if in == nil {
		return nil
	}
	out := new(InstanceClassInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVErrorInfo) DeepCopyInto(out *LVErrorInfo) {
	*out = *in
	in.LastErrorTime.DeepCopyInto(&out.LastErrorTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVErrorInfo.
func (in *LVErrorInfo) DeepCopy() *LVErrorInfo {
	if in == nil {
		return nil
	}
	out := new(LVErrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in LVPVCMap) DeepCopyInto(out *LVPVCMap) {
	{
		in := &in
		*out = make(LVPVCMap, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVPVCMap.
func (in LVPVCMap) DeepCopy() LVPVCMap {
	if in == nil {
		return nil
	}
	out := new(LVPVCMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDCluster) DeepCopyInto(out *MPDCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDCluster.
func (in *MPDCluster) DeepCopy() *MPDCluster {
	if in == nil {
		return nil
	}
	out := new(MPDCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MPDCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterCondition) DeepCopyInto(out *MPDClusterCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterCondition.
func (in *MPDClusterCondition) DeepCopy() *MPDClusterCondition {
	if in == nil {
		return nil
	}
	out := new(MPDClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterInstanceState) DeepCopyInto(out *MPDClusterInstanceState) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishAt != nil {
		in, out := &in.FinishAt, &out.FinishAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterInstanceState.
func (in *MPDClusterInstanceState) DeepCopy() *MPDClusterInstanceState {
	if in == nil {
		return nil
	}
	out := new(MPDClusterInstanceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterInstanceStatus) DeepCopyInto(out *MPDClusterInstanceStatus) {
	*out = *in
	in.VersionInfo.DeepCopyInto(&out.VersionInfo)
	out.InsClassInfo = in.InsClassInfo
	out.NetInfo = in.NetInfo
	in.CurrentState.DeepCopyInto(&out.CurrentState)
	in.LastState.DeepCopyInto(&out.LastState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterInstanceStatus.
func (in *MPDClusterInstanceStatus) DeepCopy() *MPDClusterInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(MPDClusterInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterList) DeepCopyInto(out *MPDClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MPDCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterList.
func (in *MPDClusterList) DeepCopy() *MPDClusterList {
	if in == nil {
		return nil
	}
	out := new(MPDClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MPDClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterManagerStatus) DeepCopyInto(out *MPDClusterManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterManagerStatus.
func (in *MPDClusterManagerStatus) DeepCopy() *MPDClusterManagerStatus {
	if in == nil {
		return nil
	}
	out := new(MPDClusterManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterSpec) DeepCopyInto(out *MPDClusterSpec) {
	*out = *in
	out.ClassInfo = in.ClassInfo
	out.ClassInfoModifyTo = in.ClassInfoModifyTo
	if in.ResourceAdditional != nil {
		in, out := &in.ResourceAdditional, &out.ResourceAdditional
		*out = make(map[string]AdditionalResourceCfg, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ShareStore != nil {
		in, out := &in.ShareStore, &out.ShareStore
		*out = new(ShareStoreConfig)
		**out = **in
	}
	out.DBProxyInfo = in.DBProxyInfo
	in.NetCfg.DeepCopyInto(&out.NetCfg)
	in.VersionCfg.DeepCopyInto(&out.VersionCfg)
	in.VersionCfgModifyTo.DeepCopyInto(&out.VersionCfgModifyTo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterSpec.
func (in *MPDClusterSpec) DeepCopy() *MPDClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MPDClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDClusterStatus) DeepCopyInto(out *MPDClusterStatus) {
	*out = *in
	out.InsClassInfo = in.InsClassInfo
	if in.FloatingIP != nil {
		in, out := &in.FloatingIP, &out.FloatingIP
		*out = new(FloatingIPAddr)
		**out = **in
	}
	if in.DBInstanceStatus != nil {
		in, out := &in.DBInstanceStatus, &out.DBInstanceStatus
		*out = make(map[string]*MPDClusterInstanceStatus, len(*in))
		for key, val := range *in {
			var outVal *MPDClusterInstanceStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(MPDClusterInstanceStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	out.ClusterManagerStatus = in.ClusterManagerStatus
	in.ProxyStatus.DeepCopyInto(&out.ProxyStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MPDClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDClusterStatus.
func (in *MPDClusterStatus) DeepCopy() *MPDClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MPDClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDHostLV) DeepCopyInto(out *MPDHostLV) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDHostLV.
func (in *MPDHostLV) DeepCopy() *MPDHostLV {
	if in == nil {
		return nil
	}
	out := new(MPDHostLV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDHostLVStatus) DeepCopyInto(out *MPDHostLVStatus) {
	*out = *in
	out.MPDHostLV = in.MPDHostLV
	if in.ErrorInfo != nil {
		in, out := &in.ErrorInfo, &out.ErrorInfo
		*out = new(LVErrorInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDHostLVStatus.
func (in *MPDHostLVStatus) DeepCopy() *MPDHostLVStatus {
	if in == nil {
		return nil
	}
	out := new(MPDHostLVStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDLocalVolume) DeepCopyInto(out *MPDLocalVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDLocalVolume.
func (in *MPDLocalVolume) DeepCopy() *MPDLocalVolume {
	if in == nil {
		return nil
	}
	out := new(MPDLocalVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MPDLocalVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDLocalVolumeCondition) DeepCopyInto(out *MPDLocalVolumeCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDLocalVolumeCondition.
func (in *MPDLocalVolumeCondition) DeepCopy() *MPDLocalVolumeCondition {
	if in == nil {
		return nil
	}
	out := new(MPDLocalVolumeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDLocalVolumeList) DeepCopyInto(out *MPDLocalVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MPDLocalVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDLocalVolumeList.
func (in *MPDLocalVolumeList) DeepCopy() *MPDLocalVolumeList {
	if in == nil {
		return nil
	}
	out := new(MPDLocalVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MPDLocalVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDLocalVolumeSpec) DeepCopyInto(out *MPDLocalVolumeSpec) {
	*out = *in
	if in.LvResources != nil {
		in, out := &in.LvResources, &out.LvResources
		*out = make([]MPDHostLV, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDLocalVolumeSpec.
func (in *MPDLocalVolumeSpec) DeepCopy() *MPDLocalVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(MPDLocalVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPDLocalVolumeStatus) DeepCopyInto(out *MPDLocalVolumeStatus) {
	*out = *in
	if in.LvStatus != nil {
		in, out := &in.LvStatus, &out.LvStatus
		*out = make(map[string]MPDHostLVStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PVCInfo != nil {
		in, out := &in.PVCInfo, &out.PVCInfo
		*out = make(LVPVCMap, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MPDLocalVolumeCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPDLocalVolumeStatus.
func (in *MPDLocalVolumeStatus) DeepCopy() *MPDLocalVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(MPDLocalVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxScaleInfo) DeepCopyInto(out *MaxScaleInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxScaleInfo.
func (in *MaxScaleInfo) DeepCopy() *MaxScaleInfo {
	if in == nil {
		return nil
	}
	out := new(MaxScaleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCInfo) DeepCopyInto(out *PVCInfo) {
	*out = *in
	if in.ErrorInfo != nil {
		in, out := &in.ErrorInfo, &out.ErrorInfo
		*out = new(LVErrorInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCInfo.
func (in *PVCInfo) DeepCopy() *PVCInfo {
	if in == nil {
		return nil
	}
	out := new(PVCInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShareStoreConfig) DeepCopyInto(out *ShareStoreConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShareStoreConfig.
func (in *ShareStoreConfig) DeepCopy() *ShareStoreConfig {
	if in == nil {
		return nil
	}
	out := new(ShareStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfo) DeepCopyInto(out *VersionInfo) {
	*out = *in
	if in.OtherImages != nil {
		in, out := &in.OtherImages, &out.OtherImages
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfo.
func (in *VersionInfo) DeepCopy() *VersionInfo {
	if in == nil {
		return nil
	}
	out := new(VersionInfo)
	in.DeepCopyInto(out)
	return out
}
